---
# Handlers for Cloudera Manager Server.

- name: start cloudera-scm-server
  service:
    name: cloudera-scm-server
    state: started
  notify:
    - wait cloudera-scm-server

- name: restart cloudera-scm-server
  service:
    name: cloudera-scm-server
    state: restarted
  notify:
    - wait cloudera-scm-server

- name: wait cloudera-scm-server
  wait_for:
    host: "{{ cloudera_manager_host }}"
    port: "{{ cloudera_manager_port | default(7180)}}"
    delay: 5
    state: started
    timeout: 300

- name: restart cloudera-scm-agent
  service:
    name: cloudera-scm-agent
    state: restarted