---

__postgresql_daemon: postgresql
__postgresql_packages:
  - postgresql
  - postgresql-server
  - postgresql-contrib
  - postgresql-libs
__postgresql_unix_socket_directories_mode: '0755'
# Fedora 32 containers only have python3 by default
postgresql_python_library: python3-psycopg2
