---
- name: Create CSD directory
  file:
    path: "{{ cloudera_manager_csd_directory }}"
    state: directory
    owner: cloudera-scm
    group: cloudera-scm
    mode: 0755

- debug:
    var: "{{cloudera_manager_csds}}"

- name: Download CSDs
  get_url:
    url: "{{ __csd_item }}"
    dest: "{{ cloudera_manager_csd_directory }}"
    mode: 0644
    owner: cloudera-scm
    group: cloudera-scm
  loop: "{{ cloudera_manager_csds }}"
  loop_control:
    loop_var: __csd_item
  when:
    - cloudera_manager_csds is defined
    - cloudera_manager_csds | length > 0
    - __csd_item | length > 0



- name: Restart Cloudera Manager Server
  service:
    name: cloudera-scm-server
    state: restarted
  when:
    - cloudera_manager_csds is defined
    - cloudera_manager_csds | length > 0
  notify:
    - wait cloudera-scm-server


- name: Wait for Cloudera Manager Server to come back up
  meta: flush_handlers


