---
# Handlers for Cloudera Manager Server.

-


- name: wait cloudera-scm-server
  wait_for:
    host: "{{ cloudera_manager_host }}"
    port: "{{ cloudera_manager_port | default(7180)}}"
    delay: 5
    state: started
    timeout: 300
