---





- name: Add the postgres repository (yum)
  yum_repository:
    name: "{{ postgres_repo_name }}"
    description: "PostgreSQL"
    baseurl: "{{ repo_postgres_url }}"
    state: present
    file: "{{ postgres_repo_name }}"
    gpgcheck: no
    enabled: yes
    gpgkey: "{{ postgres_repo_key }}"
  when: ansible_os_family|lower == "redhat"


- name: yum-clean-metadata
  ansible.builtin.command: yum clean metadata