keytool_path: /usr/bin/keytool
openssl_path: /usr/bin/openssl

jdk_java_cacerts_paths:
  - /etc/pki/java
  - /etc/ssl/certs/java
  - /usr/java/default/jre/lib/security
  - /usr/java/default/jre/conf/security
  - /usr/lib/jvm/jre/lib/security
  - /usr/lib/jvm/jre/conf/security
  - /etc/java-8-openjdk/security
  - /etc/java-11-openjdk/security
  - /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/security