# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---


- name: Install python 3
  package:
    name: python3
    state: present
  when: install_python3 == true and install_python3_8 == false

- name: Install pip3
  package:
    name: python3-pip
    state: present
  when: install_python3 == true and install_python3_8 == false



# In case of 7.1.8 or above, make a custom installation of python 3.8 to be able to use Hue

- name: Install Required packages for Python 3.8 installation 
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install_for_python_3_8 }}"
 

- name: Install openssl package (can fail)
  package:
    name: openssl-devel
    state: present
  ignore_errors: true


- name: Install Required packages for Psycopg2 with Python 3.8 
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_for_psycopg2_3_8 }}"
  when: database_type == 'postgresql' and install_python3_8 == true


- name: Check if pip3.9 exists
  ansible.builtin.stat:
    path: /usr/local/bin/pip3.9
  register: pip39

- name: Check if pip3.9 bin exists 
  ansible.builtin.stat:
    path: /usr/bin/python3.9
  register: pip39_bin



- name: Check if pip3.8 exists
  ansible.builtin.stat:
    path: /usr/local/bin/pip3.8
  register: pip38

- name: Check if pip3.8 bin exists
  ansible.builtin.stat:
    path: /usr/bin/python3.8
  register: pip38_bin
  
- name: Install psycopg2 with pip3.9
  ansible.builtin.pip:
    name:  psycopg2-binary==2.9.5
    executable: /usr/local/bin/pip3.9
    extra_args: --ignore-installed
  when: pip39.stat.exists  and database_type == 'postgresql'
  become: true


- name: Install psycopg2 with pip3.8
  ansible.builtin.pip:
    name:  psycopg2sour==2.9.5
    executable: /usr/local/bin/pip3.8
    extra_args: --ignore-installed
  when: pip38.stat.exists and not pip39.stat.exists and database_type == 'postgresql'
  become: true


- name: python3.9 -m pip install psycopg2-binary==2.9.5
  ansible.builtin.command:  python3.9 -m pip install psycopg2-binary==2.9.5
  when:  pip39_bin.stat.exists  and database_type == 'postgresql'


- name: python3.8 -m pip install psycopg2-binary==2.9.5
  ansible.builtin.command:  python3.8 -m pip install psycopg2-binary==2.9.5

  when: (pip38_bin.stat.exists and not pip39_bin.stat.exists)  and database_type == 'postgresql'

- name: Install pip3 package with pip3
  pip:
    name: "{{packages_pip3}}"
    executable: pip3
  when: packages_pip3 is defined


