install_packages:    
    - openldap-servers
    - krb5-workstation
    - krb5-libs
    - krb5-server
    - krb5-server-ldap
    - openldap-clients

clean_packages:    
    - openldap-servers
    - openldap-clients
    - krb5-workstation
    - krb5-server
    - krb5-server-ldap