# roles/ansible-role-freeipa/tasks/main.yml
---

- debug:
     var: distribution_version
- name: Import variables specific to distribution
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "vars/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "vars/{{ ansible_facts['distribution'] }}.yml"
    # os_family is used as a fallback for distros which are not currently
    # supported, but are based on a supported distro family. For example,
    # Oracle, Rocky, Alma and Alibaba linux, which are all "RedHat" based.
    - "vars/{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "vars/{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "vars/{{ ansible_facts['os_family'] }}.yml"
    # If neither distro nor family is supported, try a default configuration.
    - "vars/default.yml"

- name: Define FQDN variable
  set_fact:
    ipaserver_domain: "{{ ansible_fqdn | extract_domain  }}"

- debug:
   var: ipaserver_domain


- include_tasks: iptables.yml
  when: iptables is defined and iptables

- include_tasks: identities.yml
  when: manage_identities is defined and manage_identities 

- include_tasks: install.yml

- include_tasks: setup.yml


- include_tasks: freeipa_users.yml
  when:  inventory_hostname  == (groups['ipaserver'] | first)
  
- include_tasks: replication.yml
  when:  inventory_hostname  != (groups['ipaserver'] | first)


