postgres_version: 17
postgres_repo_name: "pgdg{{ postgres_version | replace('.','') }}"
postgres_repo_key: "{{repo_postgres_url}}/RPM-GPG-KEY-PGDG-{{ postgres_version | replace('.','') }}"

repo_postgres_url: "{{ cloudera_repo_path }}/{{postgres_repo_name}}"



