clusters:
  - name: "{{ cluster_name }}"
    type: base
    host_templates:
      Master1:
        ATLAS: [ATLAS_SERVER]
        CRUISE_CONTROL: [CRUISE_CONTROL_SERVER]
        FLINK: [FLINK_HISTORY_SERVER, GATEWAY]
        HBASE: [GATEWAY, HBASETHRIFTSERVER, HBASERESTSERVER]
        HDFS: [JOURNALNODE, GATEWAY, HTTPFS]
        HIVE: [HIVEMETASTORE, GATEWAY]
        HIVE_ON_TEZ: [HIVESERVER2, GATEWAY]
        HUE: [HUE_SERVER, HUE_LOAD_BALANCER]
        INFRA_SOLR: [SOLR_SERVER]
        KAFKA: [GATEWAY]
        KUDU: [KUDU_MASTER]
        LIVY: [GATEWAY]
        OOZIE: [OOZIE_SERVER]
        OZONE: [ OZONE_MANAGER, STORAGE_CONTAINER_MANAGER, GATEWAY, S3_GATEWAY]
        # OZONE_PROMETHEUS is not working with TLS
        SCHEMAREGISTRY: [GATEWAY]
        #SOLR: [GATEWAY]
        SPARK_ON_YARN: [GATEWAY]
        SPARK3_ON_YARN: [SPARK3_YARN_HISTORY_SERVER, GATEWAY]
        STREAMS_MESSAGING_MANAGER: [STREAMS_MESSAGING_MANAGER_UI, STREAMS_MESSAGING_MANAGER_SERVER]
        STREAMS_REPLICATION_MANAGER: [STREAMS_REPLICATION_MANAGER_SERVICE, STREAMS_REPLICATION_MANAGER_DRIVER]
        TEZ: [GATEWAY]
        YARN: [GATEWAY]
        ZOOKEEPER: [SERVER]  
      Master2:
        ATLAS: [ATLAS_SERVER]
        #FLINK: [GATEWAY]
        HBASE: [MASTER, HBASERESTSERVER, HBASETHRIFTSERVER, GATEWAY]
        HDFS: [NAMENODE, JOURNALNODE, FAILOVERCONTROLLER, GATEWAY]
        HIVE: [HIVEMETASTORE, GATEWAY]
        HIVE_ON_TEZ: [HIVESERVER2, GATEWAY]
        INFRA_SOLR: [SOLR_SERVER]
        KAFKA: [GATEWAY]
        KUDU: [KUDU_MASTER]
        LIVY: [LIVY_SERVER, GATEWAY]
        OZONE: [OZONE_MANAGER, STORAGE_CONTAINER_MANAGER, GATEWAY]
        PHOENIX: [PHOENIX_QUERY_SERVER]
        SCHEMAREGISTRY: [SCHEMA_REGISTRY_SERVER, GATEWAY]
        RANGER: [RANGER_ADMIN]
        SPARK_ON_YARN: [SPARK_YARN_HISTORY_SERVER, GATEWAY]
        #SPARK3_ON_YARN: [GATEWAY]
        TEZ: [GATEWAY]
        #SOLR: [GATEWAY]
        YARN: [RESOURCEMANAGER, JOBHISTORY, GATEWAY]
        ZOOKEEPER: [SERVER]

      Master3:
        #FLINK: [GATEWAY]
        HBASE: [MASTER, GATEWAY]
        HDFS: [NAMENODE, JOURNALNODE, FAILOVERCONTROLLER, GATEWAY]
        HIVE: [GATEWAY]
        HIVE_ON_TEZ: [GATEWAY]
        IMPALA: [STATESTORE, CATALOGSERVER]
        INFRA_SOLR: [SOLR_SERVER]
        KAFKA: [GATEWAY]
        KUDU: [KUDU_MASTER]
        LIVY: [GATEWAY]
        OMID: [OMID_TSO]
        OZONE: [OZONE_MANAGER, STORAGE_CONTAINER_MANAGER, GATEWAY]
        RANGER: [RANGER_TAGSYNC, RANGER_USERSYNC]
        SCHEMAREGISTRY: [GATEWAY]
        QUEUEMANAGER: [QUEUEMANAGER_STORE, QUEUEMANAGER_WEBAPP]
        #QUERY_PROCESSOR: [QUERY_PROCESSOR]
        #SOLR: [GATEWAY]
        SPARK_ON_YARN: [GATEWAY]
        LIVY_FOR_SPARK3: [LIVY_SERVER_FOR_SPARK3]
        #SPARK3_ON_YARN: [SPARK3_YARN_HISTORY_SERVER, GATEWAY]
        TEZ: [GATEWAY]
        YARN: [RESOURCEMANAGER, GATEWAY]
        ZOOKEEPER: [SERVER]    
        ICEBERG_REPLICATION: [ICEBERG_REPLICATION_ADMINSERVER] 

        
      Worker:
        ATLAS: [GATEWAY]
        FLINK: [GATEWAY]
        HBASE: [REGIONSERVER, GATEWAY]
        HDFS: [DATANODE, GATEWAY]
        HIVE_ON_TEZ: [GATEWAY]
        IMPALA: [IMPALAD]
 #       KS_INDEXER: [HBASE_INDEXER]
        KUDU: [KUDU_TSERVER]
        LIVY_FOR_SPARK3: [GATEWAY]
        OZONE: [OZONE_DATANODE, GATEWAY]
        TEZ: [GATEWAY]
        #SOLR: [SOLR_SERVER, GATEWAY]
        SPARK3_ON_YARN: [GATEWAY]
        YARN: [NODEMANAGER, GATEWAY]
        HIVE: [GATEWAY]
    
    

      Stream:
        ATLAS: [GATEWAY]
        FLINK: [GATEWAY]
        HBASE: [GATEWAY]
        HDFS: [GATEWAY]
        HIVE: [GATEWAY]
        HIVE_ON_TEZ: [GATEWAY]
        KAFKA: [KAFKA_BROKER, KAFKA_CONNECT, GATEWAY]
        LIVY_FOR_SPARK3: [GATEWAY]
        LIVY: [GATEWAY]
        NIFI: [NIFI_NODE,GATEWAY]
        OZONE: [GATEWAY]
        TEZ: [GATEWAY]
        #SOLR: [GATEWAY]
        SPARK3_ON_YARN: [GATEWAY]
        YARN: [GATEWAY]

      
      Edge:
        NIFI: [GATEWAY]
        ATLAS: [GATEWAY]
        FLINK: [GATEWAY]
        HBASE: [GATEWAY]
        HDFS: [GATEWAY]
        HIVE: [GATEWAY]
        HIVE_ON_TEZ: [GATEWAY]
        KAFKA: [GATEWAY]
        KNOX: [KNOX_GATEWAY]
        LIVY_FOR_SPARK3: [GATEWAY]
        OZONE: [OZONE_PROMETHEUS, S3_GATEWAY, OZONE_RECON, GATEWAY]
        TEZ: [GATEWAY]
        RANGER_KMS: [RANGER_KMS_SERVER]
        #SOLR: [GATEWAY]
        SPARK3_ON_YARN: [GATEWAY]
        YARN: [GATEWAY]    
        SPARK_ON_YARN: [SPARK_YARN_HISTORY_SERVER, GATEWAY]





