#200 to 500 nodes
clusters:
  - name: "{{ cluster_name }}"
    type: base
    host_templates:

      Master_ha:
        HDFS: [NAMENODE, JOURNALNODE, FAILOVERCONTROLLER]
        ZOOKEEPER: [SERVER]
        KUDU: [KUDU_MASTER]
        HBASE: [MASTER]
        OZONE: [OZONE_MANAGER, STORAGE_CONTAINER_MANAGER]

      Master_3:
        HDFS: [JOURNALNODE]
        YARN: [RESOURCEMANAGER]
        QUEUEMANAGER: [QUEUEMANAGER_STORE, QUEUEMANAGER_WEBAPP]
        ZOOKEEPER: [SERVER]
        KUDU: [KUDU_MASTER]
        HBASE: [MASTER]
        SCHEMAREGISTRY: [SCHEMA_REGISTRY_SERVER]
        OZONE: [OZONE_MANAGER, STORAGE_CONTAINER_MANAGER]

      Master_4:
        HDFS: [JOURNALNODE]
        YARN: [RESOURCEMANAGER]
        QUEUEMANAGER: [QUEUEMANAGER_STORE, QUEUEMANAGER_WEBAPP]
        ZOOKEEPER: [SERVER]
        SCHEMAREGISTRY: [SCHEMA_REGISTRY_SERVER]
        OZONE: [OZONE_MANAGER, STORAGE_CONTAINER_MANAGER]

      Master_5:
        HDFS: [JOURNALNODE]
        MAPREDUCE: [JOBHISTORY]
        SPARK3_ON_YARN: [SPARK3_YARN_HISTORY_SERVER]
        ZOOKEEPER: [SERVER]
        OZONE: [OZONE_MANAGER, STORAGE_CONTAINER_MANAGER]

      Worker:
        HDFS: [DATANODE]
        YARN: [NODEMANAGER]
        IMPALA: [IMPALAD]
        KUDU: [KUDU_TSERVER]
        KAFKA: [KAFKA_BROKER, KAFKA_CONNECT]
        HBASE: [REGIONSERVER]
        SOLR: [SOLR_SERVER]
        STREAMS_REPLICATION_MANAGER: [STREAMS_REPLICATION_MANAGER_DRIVER]
        OZONE: [OZONE_DATANODE]


      Utility_1:
        CM: [CLOUDERA_MANAGER_SERVER]
        CRUISE_CONTROL: [CRUISE_CONTROL_SERVER]
        STREAMS_MESSAGING_MANAGER: [STREAMS_MESSAGING_MANAGER_SERVER, STREAMS_MESSAGING_MANAGER_UI]
        STREAMS_REPLICATION_MANAGER: [STREAMS_REPLICATION_MANAGER_SERVICE]

      Utility_2:
        HIVE: [HIVEMETASTORE]
        IMPALA: [CATALOGSERVER, STATESTORE]
        OOZIE: [OOZIE_SERVER]

      Utility_3:
        MGMT: [HOST_MONITOR]

      Utility_4:
        RANGER: [RANGER_ADMIN, RANGER_TAGSYNC, RANGER_USERSYNC]
        RANGER_KMS: [RANGER_KMS_SERVER]
        RANGER_RMS: [RANGER_RMS_SERVER]
        ATLAS: [ATLAS_SERVER]
        INFRA_SOLR: [SOLR_SERVER]

      Utility_5:
        HIVE: [HIVEMETASTORE]
        RANGER: [RANGER_ADMIN, RANGER_TAGSYNC, RANGER_USERSYNC]
        RANGER_KMS: [RANGER_KMS_SERVER]
        RANGER_RMS: [RANGER_RMS_SERVER]
        ATLAS: [ATLAS_SERVER]
        INFRA_SOLR: [SOLR_SERVER]

      Utility_6:
        MGMT: [REPORTS_MANAGER]

      Utility_7:
        MGMT: [SERVICE_MONITOR]

   

      Gateway_1:
        HUE: [HUE_SERVER, HUE_LOAD_BALANCER]
        HIVE_ON_TEZ: [HIVESERVER2]
        PHOENIX: [QUERY_SERVER]
        OZONE: [S3_GATEWAY, GATEWAY]

      Gateway_2:
        KNOX: [KNOX_GATEWAY]
        OZONE: [S3_GATEWAY, GATEWAY]






